CREATE TABLE STUDENT(STUDENT_ID  INT,
                      STUDENT_NAME  CHAR(10),
                      STUDENT_CLASS  CHAR(1),
                      STUDENT_AGE  INT,
                      STUDENT_DEPATMENT VARCHAR(50));



OUTPUT:
/*STUDENTS
STUDENTS_ID	STUDENTS_NAME	STUDENTS_CLASS	STUDENT_AGE	STUDENT_DEPATMENT
empty*/
