CREATE TABLE STUDENTS(
STUDENT_ID INT,
STUDENT_NAME CHAR(10),
STUDENT_AGE INT,
STUDENT_DEPARTMENT VARCHAR(50)
);

INSERT INTO STUDENTS(
  STUDENT_ID,
  STUDENT_NAME,
  STUDENT_AGE,
  STUDENT_DEPARTMENT 
)

VALUES(
  3456,
  'GOKUL',
  23,
  'EEE'
);

UPDATE STUDENTS
  SET STUDENT_DEPARTMENT = 'CSE',
  STUDENT_NAME = 'NAN'
  WHERE STUDENT_ID = 3456;
  
  SELECT * FROM STUDENTS;


/*STUDENT_ID	STUDENT_NAME	STUDENT_AGE	STUDENT_DEPARTMENT
3456	GOKUL	23	EEE*/
  

--OUTPUT

/*STUDENT_ID	STUDENT_NAME	STUDENT_AGE	STUDENT_DEPARTMENT
3456	NAN	23	CSE*/
