CREATE TABLE STUDENTS(
  STUDENT_NAME CHAR(10),
  STUDENT_ID INT,
  STUDENT_MARKS INT,
  STUDENT_DEPARTMENT VARCHAR(50)
);


INSERT INTO STUDENTS VALUES('GOKS',123,78,'CS');
INSERT INTO STUDENTS VALUES('MAMS',124,87,'CS');
INSERT INTO STUDENTS VALUES('DADS',125,99,'CS');
INSERT INTO STUDENTS VALUES('SSIS',127,58,'CS');
INSERT INTO STUDENTS VALUES('FDES',126,88,'CS');

SELECT * FROM STUDENTS;

/*STUDENT_NAME	STUDENT_ID	STUDENT_MARKS	STUDENT_DEPARTMENT
GOKS	123	78	CS
MAMS	124	87	CS
DADS	125	99	CS
SSIS	127	58	CS
FDES	126	88	CS*/

--COUNT()
SELECT COUNT (STUDENT_ID)
FROM STUDENTS;

--5

--SUM()

SELECT SUM(STUDENT_MARKS)
FROM STUDENTS;

/*78 + 87 + 99 + 58 + 88 = 410
Result: Total student marks = 410*/

--AVG()

SELECT AVG(STUDENT_MARKS)
FROM STUDENTS;

/*Calculation:

(78 + 87 + 99 + 58 + 88) / 5 = 410 / 5 = 82
Result: Average student marks = 82*/

--max() AND MIN()

SELECT MAX(STUDENT_MARKS)
FROM STUDENTS;

/*| MAX(STUDENT_MARKS) |
| -----------------: |
|                 99 |
*/
